### ISSUE TITLE
Report un-named PML construct

### ISSUE THREAD

**Issue by houli** [tom-and-the-toothfairies/pathways#141]
Collect line numbers of unnamed constructs and their types during parse to report something like `unnamed branch on line 32`

**Comment by c-brenn** [comment]
As the resident compiler wizard, do you think this can all be done in the parse - or are you thinking we build an AST in parse then analyse it?

**Comment by c-brenn** [comment]
Need to ask him which constructs require names. His intention seemed to be that constructs have some unique identifier. Does the user have to specify these, or can they be generated?

Seems a bit mad that you would have to name your branches and selections (not very usable).

**Comment by houli** [comment]
Information is all there, just need to display it

**Comment by laurmurclar** [comment]
@c-brenn he wanted to use the identifiers so that it would be easy to target them for transformations. Seems like he wanted the user to have named them in the original upload and then generate new identifiers as the transformations created new constructs. If we were picking the constructs with a GUI rather than CLI, he might just allow us to ignore that feature.

**Comment by c-brenn** [comment]
definitely something we should discuss with him at the next meeting. As @laurmurclar said, the GUI could make this redundant. Could be a similar situation to our `select and ontology` feature. Where he's happy with a different approach as long as it achieves the same overall goal

**Comment by ajenner** [comment]
#153 implements this, although further discussion RE: styling may be needed before this is closed

**Comment by c-brenn** [comment]
Seems it's just UI discussion left here. Closing this issue - we can move any discussion to #162
