### ISSUE TITLE
Select specific OWL Ontology

### ISSUE THREAD

**Issue by shawa** [tom-and-the-toothfairies/pathways#15]

**Comment by shawa** [comment]
Added an environment variable setting to set this on startup:

https://github.com/tom-and-the-toothfairies/pathways/pull/36/commits/c859bfd659ffbe1bf5b38cc06c8a8de56f0e1961

**Comment by 22a** [comment]
The customer has indicated that this feature can be satisfied by adding a section to the documentation detailing the fact that, in the unlikely event that dinto ever gets updated, in order to add the update to our application one could simply:
1. fork the chiron image
2. replace the dinto repo/hash with the new one
3. rewrite the composefile to use that image instead

**Comment by c-brenn** [comment]
At the moment, Chiron's Dockerfile clones DINTO, checks out a specific commit and then uses DINTO_1.owl

Perhaps a better solution would be to `curl` the specific version from github - with a url like this:
`https://raw.githubusercontent.com/labda/DINTO/68a29b568d6690fd04284feb06d152ca6e1e2e46/DINTO%201/DINTO_1.owl`

 The url could be stored as an `ENV` variable in the dockerfile. This would allow the ontology file to be changed easily.

**Comment by 22a** [comment]
resolved by https://github.com/tom-and-the-toothfairies/pathways/pull/120
